<a href="https://colab.research.google.com/github/dasuntheekshanagit/COMLab/blob/master/COMNUMPY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [64]:
 
import numpy as np
test1 = np.array([1,2,3])
#print(type(test1))
print(test1.shape)
print(test1.size)

(3,)
3


In [ ]:
b = np.array([[1],[2],[3],[4]])
print(b.shape,b.size)

(4, 1) 4


In [ ]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
c = np.linspace(1,100)
print(c,c.size)
d = np.linspace(1,100,100)
print(d,d.size)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ] 50
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  6

In [ ]:
x = np.arange(1,17)
x = np.reshape(x,(4,4))
print(x)
print(x[1:3,1:3])
y= x[1:3,1:3]
y[:,:]=0
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]
[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]
 [13 14 15 16]]


In [ ]:
 x = np.arange(1,17)
x = np.reshape(x,(4,4))
print(x)
print(x[1:3,1:3])
y= x[1:3,1:3].copy()
y[:,:]=0
print(y)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]
[[0 0]
 [0 0]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
 
#Fancy indexing 
a = np.linspace(0,1,11)
print(a)
print(a>0.5)
print(a[a>0.5])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[False False False False False False  True  True  True  True  True]
[0.6 0.7 0.8 0.9 1. ]


In [ ]:
y = np.arange(1,26).reshape(5,5)
print(y)
print(np.random.rand(12).reshape(3,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[0.68554769 0.53162416 0.0327171  0.66314664]
 [0.59866142 0.64325544 0.39926124 0.55104455]
 [0.94836872 0.25298034 0.93094283 0.12784236]]


In [27]:
 y= np.arange(1,17).reshape(4,4)
x[0,0]=10
print(x)
x[3,:]=3
print(x)
x[:,1]=2
print(x)

[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 3  3  3  3]]
[[10  2  3  4]
 [ 5  2  7  8]
 [ 9  2 11 12]
 [ 3  2  3  3]]


In [33]:
a = np.arange(1,26).reshape(5,5)
b = np.arange(1,26).reshape(5,5)
c = np.concatenate((a,b))#raw wise
print(a)
print(c)
d = np.concatenate((a,b),axis=1)#colomun wuse
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]
 [11 12 13 14 15 11 12 13 14 15]
 [16 17 18 19 20 16 17 18 19 20]
 [21 22 23 24 25 21 22 23 24 25]]


In [37]:
print(np.hstack((a,b))) # colom wise
print(np.vstack((a,b))) # raw wise

[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]
 [11 12 13 14 15 11 12 13 14 15]
 [16 17 18 19 20 16 17 18 19 20]
 [21 22 23 24 25 21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [56]:
# Matrix Operations 
A = np.array([[1,2],[3,4]])
print(A)
print(A.T)
B = np.array([[1,2],[3,4]])
print(A+B)
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B)) #element wise
print(np.dot(A,B)) #Matrix wiseprint(np.divide(A,B))
#print(np.log(A,B))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[2 4]
 [6 8]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [60]:
 print(np.mean(A))
print(np.mean(A,axis = 0)) #row wise
print(np.mean(A,axis =1)) #colom wise

2.5
[2. 3.]
[1.5 3.5]


In [74]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
print(np.linalg.solve(a,b))

[[1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00]]


$p_1 = x^3 + 2\cdot x -7$

In [79]:
p1 = np.array([1,0,2,-7])
print(np.roots(p1))

[-0.7844732+1.96117174j -0.7844732-1.96117174j  1.5689464+0.j        ]
[ 1. -6. 11. -6.]


In [81]:
 print(np.poly([1,2,3]))# Coefficient
root = [1,2]
print(np.poly(root))
f = np.poly(root)

[ 1. -6. 11. -6.]
[ 1. -3.  2.]


$ x^2 - 3\cdot x +2$

In [84]:
print(np.polyval(f,0)) # x =0

2.0
